### PR TITLE
Added new type of request and it's method 

### PR DESCRIPTION
**Pull request by kirki333**
Hello :) I expanded the usage and now it's possible for someone to see all the categories of the questions and the number of questions each one has. I think it is a useful feature. Hope you like it! 

In the README.md file the new documentation will be:

**To show all the categories and their number of questions**
curl -X GET \
 http://127.0.0.1:5000/show-all-categories

### CODE REVIEW

**Comment by allEyezOnCode** [comment]
Thanks for contributing ! I'll merge it, can you add this requests forn multiple choice question (make a new Pull Requests) ?

**Comment by kirki333** [comment]
You mean a method for showing all the categories but in the MultiChoiceQuestion.py?

**Comment by allEyezOnCode** [comment]
A new request is good but if you want to implement a new function for show showing all category you can.

**Comment by kirki333** [comment]
Ok I am making a new request, I am sending the new pull request in a bit.

**Comment by kirki333** [comment]
Do you want me to add the new requests in the README.md file also?

**Comment by allEyezOnCode** [comment]
@kirki333 sure

**Pull request merged**
